name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto a la rama que quieras desplegar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Asegúrate de que la versión de Node.js sea compatible

      - name: Install dependencies and build
        uses: withastro/action@v2
        with:
          package-manager: npm  # Cambia a "yarn" o "pnpm" según el gestor que uses
